"""ABLATION: does PFGT-UIE enhancement help downstream underwater detection?

This is the experiment session 1's report recommended, and it is the question that
actually matters for the AUV use case — more than another 0.2 dB of PSNR.

`infer_detection.py` currently runs `raw -> PFGT-UIE enhance -> detect`. But the RUOD
detector was fine-tuned on *raw* RUOD frames. Enhancing at inference time therefore feeds
it a distribution it never trained on. So there are two distinct questions:

  Q1 (deployed pipeline, what this script answers):
      Detector trained on RAW. Evaluate on RAW vs on ENHANCED.
      -> Does the repo's existing enhance-then-detect path help or hurt *today*?

  Q2 (matched-domain, a further experiment):
      Fine-tune a detector on ENHANCED frames, evaluate on ENHANCED.
      -> Does enhancement help when the detector is adapted to it?

Q1 alone cannot conclude "enhancement is bad for detection" — a drop there is confounded
with train/test domain shift. It CAN conclude something immediately actionable: whether the
pipeline as currently wired is helping or hurting itself.

Enhancement is applied at native resolution (padded to a multiple of 16, then cropped),
exactly as `infer_detection.py` does, so the ablation measures the real pipeline.

Usage:
    python tools/ablation_enhance_detect.py --limit 1200
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import time
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np
import torch
import torch.nn.functional as F
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "datasets" / "RUOD_yolo"
DST = ROOT / "datasets" / "RUOD_yolo_enhanced"

CLASS_NAMES = [
    "holothurian", "echinus", "scallop", "starfish", "fish",
    "corals", "diver", "cuttlefish", "turtle", "jellyfish",
]


def link_or_copy(src: Path, dst: Path) -> None:
    if dst.exists():
        return
    try:
        os.symlink(src, dst)
    except (OSError, NotImplementedError, AttributeError):
        shutil.copy2(src, dst)


def build_enhanced_val(enhancer, names: list[str], device: str, max_side: int | None) -> dict:
    """Write enhanced copies of the chosen val images, symlinking their labels."""
    img_out = DST / "images" / "val"
    lbl_out = DST / "labels" / "val"
    img_out.mkdir(parents=True, exist_ok=True)
    lbl_out.mkdir(parents=True, exist_ok=True)

    src_img = SRC / "images" / "val"
    src_lbl = SRC / "labels" / "val"

    t0 = time.time()
    done = 0
    for name in names:
        out_path = img_out / name
        lbl_src = src_lbl / f"{Path(name).stem}.txt"
        link_or_copy(lbl_src, lbl_out / f"{Path(name).stem}.txt")
        if out_path.exists():
            done += 1
            continue

        with Image.open(src_img / name) as im:
            im = im.convert("RGB")
            w0, h0 = im.size
            if max_side and max(w0, h0) > max_side:
                scale = max_side / max(w0, h0)
                im_proc = im.resize((int(w0 * scale), int(h0 * scale)), Image.Resampling.BILINEAR)
            else:
                im_proc = im
            arr = np.array(im_proc, dtype=np.float32) / 255.0

        t = torch.from_numpy(arr).permute(2, 0, 1).unsqueeze(0).to(device)
        _, _, h, w = t.shape
        ph, pw = (16 - h % 16) % 16, (16 - w % 16) % 16
        if ph or pw:
            t = F.pad(t, (0, pw, 0, ph), mode="reflect")
        with torch.no_grad():
            y = enhancer(t)
        y = y[:, :, :h, :w]
        out = (y.squeeze(0).clamp(0, 1).cpu().numpy().transpose(1, 2, 0) * 255).astype(np.uint8)
        img = Image.fromarray(out)
        if img.size != (w0, h0):
            img = img.resize((w0, h0), Image.Resampling.BILINEAR)
        img.save(out_path, quality=95)
        done += 1
        if done % 200 == 0:
            el = time.time() - t0
            print(f"  enhanced {done}/{len(names)}  ({el/done:.2f}s/img, "
                  f"ETA {(len(names)-done)*el/done/60:.1f} min)", flush=True)

    yaml_path = DST / "ruod_enhanced.yaml"
    names_block = "\n".join(f"  {i}: {n}" for i, n in enumerate(CLASS_NAMES))
    yaml_path.write_text(
        "# RUOD val, PFGT-UIE enhanced (ablation). Generated by tools/ablation_enhance_detect.py\n"
        f"path: {DST.as_posix()}\n"
        "train: images/val\n"   # unused; ultralytics wants the key present
        "val: images/val\n\n"
        "names:\n" + names_block + "\n",
        encoding="utf-8",
    )
    return {"count": done, "seconds": time.time() - t0, "yaml": str(yaml_path)}


def build_raw_subset(names: list[str]) -> Path:
    """A raw-image dataset restricted to the same images, so the comparison is paired."""
    sub = ROOT / "datasets" / "RUOD_yolo_rawsubset"
    (sub / "images" / "val").mkdir(parents=True, exist_ok=True)
    (sub / "labels" / "val").mkdir(parents=True, exist_ok=True)
    for name in names:
        link_or_copy(SRC / "images" / "val" / name, sub / "images" / "val" / name)
        link_or_copy(SRC / "labels" / "val" / f"{Path(name).stem}.txt",
                     sub / "labels" / "val" / f"{Path(name).stem}.txt")
    names_block = "\n".join(f"  {i}: {n}" for i, n in enumerate(CLASS_NAMES))
    y = sub / "ruod_rawsubset.yaml"
    y.write_text(
        "# RUOD val subset, raw images (ablation control).\n"
        f"path: {sub.as_posix()}\n"
        "train: images/val\n"
        "val: images/val\n\n"
        "names:\n" + names_block + "\n",
        encoding="utf-8",
    )
    return y


def evaluate(weights: Path, data_yaml: Path, imgsz: int, tag: str) -> dict:
    from ultralytics import YOLO
    model = YOLO(str(weights))
    m = model.val(data=str(data_yaml), imgsz=imgsz, device=0 if torch.cuda.is_available() else "cpu",
                  verbose=False, plots=False, split="val")
    box = m.box
    names = m.names if isinstance(m.names, dict) else {}
    per_class = {}
    try:
        for i, ci in enumerate(box.ap_class_index):
            per_class[names.get(int(ci), str(ci))] = {
                "AP50": round(float(box.ap50[i]), 4),
                "AP50_95": round(float(box.ap[i]), 4),
            }
    except Exception:
        pass
    res = {
        "condition": tag,
        "mAP50": round(float(box.map50), 4),
        "mAP50_95": round(float(box.map), 4),
        "precision": round(float(box.mp), 4),
        "recall": round(float(box.mr), 4),
        "per_class": per_class,
    }
    print(f"  [{tag}] mAP50={res['mAP50']:.4f}  mAP50-95={res['mAP50_95']:.4f}  "
          f"P={res['precision']:.4f}  R={res['recall']:.4f}")
    return res


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--enhancer", default="checkpoints/best.pt")
    ap.add_argument("--detector", default="checkpoints/detector/best.pt")
    ap.add_argument("--limit", type=int, default=1200,
                    help="Number of val images (paired across both conditions)")
    ap.add_argument("--imgsz", type=int, default=640)
    ap.add_argument("--max-side", type=int, default=1280,
                    help="Cap the long side before enhancement (0 = true native)")
    ap.add_argument("--out", default="results/ablation_enhance_detect.json")
    args = ap.parse_args()

    device = "cuda" if torch.cuda.is_available() else "cpu"
    all_names = sorted(p.name for p in (SRC / "images" / "val").glob("*.jpg"))
    names = all_names[: args.limit] if args.limit else all_names
    print(f"Ablation on {len(names)} RUOD val images (paired)\n")

    from models.build import build_model
    from utils.checkpoint import load_checkpoint
    enhancer = build_model(device=device)
    load_checkpoint(args.enhancer, model=enhancer, device=torch.device(device))
    enhancer.eval()

    print("Building enhanced copies ...")
    info = build_enhanced_val(enhancer, names, device,
                              args.max_side if args.max_side else None)
    print(f"  {info['count']} images in {info['seconds']/60:.1f} min\n")
    del enhancer
    torch.cuda.empty_cache()

    raw_yaml = build_raw_subset(names)
    enh_yaml = Path(info["yaml"])

    weights = ROOT / args.detector
    print("Evaluating detector (fine-tuned on RAW RUOD):")
    raw_res = evaluate(weights, raw_yaml, args.imgsz, "raw")
    enh_res = evaluate(weights, enh_yaml, args.imgsz, "enhanced")

    delta50 = enh_res["mAP50"] - raw_res["mAP50"]
    delta5095 = enh_res["mAP50_95"] - raw_res["mAP50_95"]

    per_class_delta = {}
    for cls in CLASS_NAMES:
        r = raw_res["per_class"].get(cls)
        e = enh_res["per_class"].get(cls)
        if r and e:
            per_class_delta[cls] = round(e["AP50"] - r["AP50"], 4)

    summary = {
        "question": "Does PFGT-UIE enhancement help the RUOD detector that was fine-tuned on RAW images?",
        "images": len(names),
        "enhancer_checkpoint": args.enhancer,
        "detector_checkpoint": args.detector,
        "imgsz": args.imgsz,
        "max_side_before_enhancement": args.max_side,
        "raw": raw_res,
        "enhanced": enh_res,
        "delta_mAP50": round(delta50, 4),
        "delta_mAP50_95": round(delta5095, 4),
        "per_class_delta_AP50": per_class_delta,
        "caveat": ("The detector was fine-tuned on RAW RUOD frames, so evaluating it on "
                   "enhanced frames introduces a train/test domain shift. A drop here means "
                   "the CURRENTLY WIRED enhance-then-detect pipeline hurts; it does NOT by "
                   "itself prove enhancement is unhelpful for detection in general. The "
                   "matched-domain test is to fine-tune on enhanced frames."),
    }

    out_path = ROOT / args.out
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print("\n" + "=" * 68)
    print(f"  raw      : mAP50 {raw_res['mAP50']:.4f}   mAP50-95 {raw_res['mAP50_95']:.4f}")
    print(f"  enhanced : mAP50 {enh_res['mAP50']:.4f}   mAP50-95 {enh_res['mAP50_95']:.4f}")
    print(f"  delta    : mAP50 {delta50:+.4f}   mAP50-95 {delta5095:+.4f}")
    print("=" * 68)
    if per_class_delta:
        print("  per-class AP50 delta (enhanced - raw):")
        for cls, d in sorted(per_class_delta.items(), key=lambda kv: kv[1], reverse=True):
            print(f"    {cls:<14} {d:+.4f}")
    print(f"\nsaved -> {args.out}")


if __name__ == "__main__":
    main()
